#!/usr/bin/env bash
# This script parses /etc/passwd and displays specific user details

while IFS=":" read -r username _ uid _ _ home _; do
	echo "User: $username, ID: $uid, Home: $home"
done < /etc/passwd
