#!/usr/bin/env bash
# This script parses /etc/passwd and displays specific user details

while IFS=":" read -r username _password uid _gid _info home _shell; do
	echo "User: $username, ID: $uid, Home: $home"
done < /etc/passwd
